In [1]:
import pandas as pd 
import os
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [2]:
regex_str = r'^(?n:(?<address1>(\d{1,5}(\ 1\/[234])?(\x20[A-Z]([a-z])+)+ )|(P\.O\.\ Box\ \d{1,5}))\s{1,2}(?i:(?<address2>(((APT|B LDG|DEPT|FL|HNGR|LOT|PIER|RM|S(LIP|PC|T(E|OP))|TRLR|UNIT)\x20\w{1,5})|(BSMT|FRNT|LBBY|LOWR|OFC|PH|REAR|SIDE|UPPR)\.?)\s{1,2})?)(?<city>[A-Z]([a-z])+(\.?)(\x20[A-Z]([a-z])+){0,2})\, \x20(?<state>A[LKSZRAP]|C[AOT]|D[EC]|F[LM]|G[AU]|HI|I[ADL N]|K[SY]|LA|M[ADEHINOPST]|N[CDEHJMVY]|O[HKR]|P[ARW]|RI|S[CD] |T[NX]|UT|V[AIT]|W[AIVY])\x20(?<zipcode>(?!0{5})\d{5}(-\d {4})?))$'


def regex_address_extract(row):
    regex = re.compile(regex_str % re.escape(string.punctuation))
    regex.sub('', row)
#     print(f'PPunct: {row}')


    # r = re.compile(r'^(?<address1>(?>\d{1,6}(?>\ 1\/[234])?( (N(orth)?|S(outh)?)? ?(E(ast)?|W(est)?))?((?> \d+ ?(th|rd|st|nd))|(?> [A-Z](?>[a-z])+)+) (?>(?i)THROUGHWAY|TRAFFICWAY|CROSSROADS|EXPRESSWAY|BOULEVARD|CROSSROAD|EXTENSION|JUNCTIONS|MOUNTAINS|STRAVENUE|UNDERPASS|CAUSEWAY|CRESCENT|CROSSING|JUNCTION|MOTORWAY|MOUNTAIN|OVERPASS|PARKWAYS|TURNPIKE|VILLIAGE|VILLAGES|CENTERS|CIRCLES|COMMONS|CORNERS|ESTATES|EXPRESS|FORESTS|FREEWAY|GARDENS|GATEWAY|HARBORS|HIGHWAY|HOLLOWS|ISLANDS|JUNCTON|LANDING|MEADOWS|MOUNTIN|ORCHARD|PARKWAY|PASSAGE|PRAIRIE|RANCHES|SPRINGS|SQUARES|STATION|STRAVEN|STRVNUE|STREETS|TERRACE|TRAILER|TUNNELS|VALLEYS|VIADUCT|VILLAGE|ALLEE|ARCADE|AVENUE|BLUFFS|BOTTOM|BRANCH|BRIDGE|BROOKS|BYPASS|CANYON|CAUSWA|CENTER|CENTRE|CIRCLE|CLIFFS|COMMON|CORNER|COURSE|COURTS|CRSENT|CRSSNG|DIVIDE|DRIVES|ESTATE|EXTNSN|FIELDS|FOREST|FORGES|FREEWY|GARDEN|GATEWY|GATWAY|GREENS|GROVES|HARBOR|HIGHWY|HOLLOW|ISLAND|ISLNDS|JCTION|JUNCTN|KNOLLS|LIGHTS|MANORS|MEADOW|MEDOWS|MNTAIN|ORCHRD|PARKWY|PLAINS|POINTS|RADIAL|RADIEL|RAPIDS|RIDGES|SHOALS|SHOARS|SHORES|SKYWAY|SPRING|SPRNGS|SQUARE|STRAVN|STREAM|STREME|STREET|SUMITT|SUMMIT|TRACES|TRACKS|TRAILS|TUNNEL|TURNPK|UNIONS|VALLEY|VIADCT|VILLAG|ALLEE|ALLEY|ANNEX|AVENU|AVNUE|BAYOO|BAYOU|BEACH|BLUFF|BOTTM|BOULV|BRNCH|BRDGE|BROOK|BURGS|BYPAS|CANYN|CENTR|CNTER|CIRCL|CRCLE|CLIFF|COURT|COVES|CREEK|CRSNT|CREST|CURVE|DRIVE|FALLS|FERRY|FIELD|FLATS|FORDS|FORGE|FORKS|FRWAY|GARDN|GRDEN|GRDNS|GTWAY|GLENS|GREEN|GROVE|HARBR|HRBOR|HAVEN|HIWAY|HILLS|HOLWS|ISLND|ISLES|JCTNS|KNOLL|LAKES|LNDNG|LIGHT|LOCKS|LODGE|LOOPS|MANOR|MILLS|MISSN|MOUNT|MNTNS|PARKS|PKWAY|PKWYS|PATHS|PIKES|PINES|PLAIN|PLAZA|POINT|PORTS|RANCH|RNCHS|RAPID|RIDGE|RIVER|ROADS|ROUTE|SHOAL|SHOAR|SHORE|SPRNG|SPNGS|SPURS|STATN|STRAV|STRVN|SUMIT|TRACE|TRACK|TRAIL|TRLRS|TUNEL|TUNLS|TUNNL|TRNPK|UNION|VALLY|VIEWS|VILLG|VILLE|VISTA|WALKS|WELLS|ALLY|ANEX|ANNX|AVEN|BEND|BLUF|BLVD|BOUL|BURG|BYPA|BYPS|CAMP|CNYN|CAPE|CSWY|CENT|CNTR|CIRC|CRCL|CLFS|CLUB|CORS|CRSE|COVE|CRES|XING|DALE|DRIV|ESTS|EXPR|EXPW|EXPY|EXTN|EXTS|FALL|FRRY|FLDS|FLAT|FLTS|FORD|FRST|FORG|FORK|FRKS|FORT|FRWY|GRDN|GDNS|GTWY|GLEN|GROV|HARB|HIWY|HWAY|HILL|HLLW|HOLW|INLT|ISLE|JCTN|JCTS|KEYS|KNOL|KNLS|LAKE|LAND|LNDG|LANE|LOAF|LOCK|LCKS|LDGE|LODG|LOOP|MALL|MNRS|MDWS|MEWS|MILL|MSSN|MNTN|MTIN|NECK|ORCH|OVAL|PARK|PKWY|PASS|PATH|PIKE|PINE|PNES|PLNS|PLZA|PORT|PRTS|RADL|RAMP|RNCH|RPDS|REST|RDGE|RDGS|RIVR|ROAD|SHLS|SHRS|SPNG|SPGS|SPUR|SQRE|SQRS|STRA|STRM|STRT|TERR|TRCE|TRAK|TRKS|TRLS|TRLR|TUNL|VLLY|VLYS|VDCT|VIEW|VILL|VLGS|VIST|VSTA|WALK|WALL|WAYS|WELL|ALY|ANX|ARC|AVE|AVN|BCH|BND|BLF|BOT|BTM|BRG|BRK|BYP|CMP|CPE|CEN|CTR|CIR|CLF|CLB|COR|CTS|CRK|DAM|DIV|DVD|DRV|EST|EXP|EXT|FLS|FRY|FLD|FLT|FRD|FRG|FRK|FRT|FWY|GLN|GRN|GRV|HBR|HVN|HTS|HWY|HLS|ISS|JCT|KEY|KYS|KNL|LKS|LGT|LCK|LDG|MNR|MDW|MNT|MTN|NCK|OVL|PRK|PKY|PLN|PLZ|PTS|PRT|PRR|RAD|RPD|RST|RDG|RIV|RVR|RDS|ROW|RUE|RUN|SHL|SHR|SPG|SQR|SQU|STA|STN|STR|SMT|TER|TRK|TRL|VLY|VIA|VWS|VLG|VIS|VST|WAY|WLS|AV|BR|CP|CT|CV|DL|DM|DV|DR|FT|HT|HL|IS|KY|LK|LN|LF|MT|PL|PT|PR|RD|SQ|ST|UN|VW|VL|WY))( (N(orth)?|S(outh)?)? ?(E(ast)?|W(est)?)?)?)$')
    addresses = []
    [addresses.append(item) for item in r.findall(object) if item not in addresses]
    return addresses

In [3]:
from ast import literal_eval
# literal_eval('[1.23, 2.34]')

def extract_phone_numbers(string):

    r = re.compile(r'(\d{3}[-\.\s]??\d{3}[-\.\s]??\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]??\d{4}|\d{3}[-\.\s]??\d{4})')
    phone_numbers = r.findall(string)
    numbers =  [re.sub(r'\D', '', number) for number in phone_numbers]
    extracted_numbers = []
    [extracted_numbers.append(number) for number in numbers if number not in extracted_numbers]
    return extracted_numbers

def de_list(l):
    if len(l) > 1:
        literal_eval(l)

In [4]:
def extract_email_addresses(string):

    r = re.compile(r'[\w\.-]+@[\w\.-]+')
    emails = []
    [emails.append(item) for item in r.findall(string) if item not in emails]
    return emails

In [112]:
import string

def ie_preprocess(document):

    
    document = ' '.join([i for i in document.split() if i not in stop])
    sentences = nltk.sent_tokenize(document)
    sentences = [nltk.word_tokenize(sent) for sent in sentences]
    sentences = [nltk.pos_tag(sent) for sent in sentences]
    return sentences


def extract_names(document, address):


    names = []
    sentences = ie_preprocess(document)
    for tagged_sentence in sentences:
        for chunk in nltk.ne_chunk(tagged_sentence):
            if type(chunk) == nltk.tree.Tree:
                if chunk.label() == 'PERSON':
                    names.append(' '.join([c[0] for c in chunk]))
    extracted_names = []
    [extracted_names.append(name) for name in names if name not in extracted_names]

#     names_checked = []

#     for name in name_list:
#         for item in extracted_names:
#             if name in item.lower():
#                 if item not in names_checked:
#                     names_checked.append(item)

#     first_names = [x.split()[0] for x in names_checked]
# #     print(f'NAMES_CHECKED BEFORE CLEANING: {names_checked}')

#     for name in names_checked:
#         if name in address:
#             names_checked.remove(name)
#     for name in names_checked:
#         if name in first_names:
#             names_checked.remove(name)

    return extracted_names

def replace_html(cell):
    cell.replace('<br>', ' ')
    cell.replace('\n', ' ')
    return cell


def easy_name(cell):
    """ Clear Hou at end, moms, mom, house """
    try:
        if cell.endswith('hou'):
            cell = cell.rstrip('hou')

        if cell.endswith('Hou'):
            cell = cell.rstrip('Hou')

        if cell.endswith('moms'):
            cell = cell.rstrip('moms')

        if cell.endswith('Moms'):
            cell = cell.rstrip('Moms')

        if cell.endswith('house'):
            cell = cell.rstrip('house')
        if cell.endswith('Hom'):
            cell = cell.rstrip('Hom')
        if type(cell) == 'NoneType':
            cell = ''
    except:
        return cell
    
    return cell

def last_name(cell):
    try:
        cell = cell.split()
        if len(cell) > 1:
            last_name = cell[-1]
            return last_name
        else:
            return ''.join(cell)
    except:
        return cell
    
def first_name(cell):
    try:
        full = cell.split()
        first = ' '.join(full[: len(full) - 1])
        return first
    except:
        return cell

def cap_words(s):
    s = string.capwords(s)
    return s

In [50]:
name_list = []
with open('NAMES.DIC', 'r') as f:
    for _ in f:
        name_list.append(_.strip())
        

        import argparse
import json
import os

from rosette.api import API, DocumentParameters, RosetteException


def run(key, entities_text_data, alt_url='https://api.rosette.com/rest/v1/'):
    """ Run the example """
    # Create an API instance
    api = API(user_key=key, service_url=alt_url)

    # Set selected API options.
    # For more information on the functionality of these
    # and other available options, see Rosette Features & Functions
    # https://developer.rosette.com/features-and-functions#entity-extraction-and-linking

    # api.set_option('calculateSalience','true')
    # api.set_option('linkEntities','false')


    params = DocumentParameters()
    params["content"] = entities_text_data
    params["genre"] = "social-media"
    try:
        return api.entities(params)
    except RosetteException as exception:
        print(exception)

def return_rosette(x):
    RESULT = run(key='8ef3dd8a2669509d1165bcf5e21596e7', entities_text_data=x)
    RESULT = json.dumps(RESULT, indent=2, ensure_ascii=False, sort_keys=True)
    RESULT = json.loads(RESULT)
    try:
        target_facet_name = 'PERSON'
        for record in RESULT["entities"]:
            if record["type"] == target_facet_name:
                return record["normalized"]
    except:
        return ''

In [7]:
os.chdir('Customer Data CLEANED CSV/subset')
DATA_FILE = '4-9-2020 - MASTER M.csv'
os.listdir()
os.getcwd()
# "2017 Data.csv" has null values for Name and Address

'C:\\Users\\james\\Desktop\\repository\\Couillard_data\\Customer Data CLEANED CSV\\subset'

In [130]:
os.listdir()
from ast import literal_eval
# literal_eval('[1.23, 2.34]')

df = pd.read_csv(DATA_FILE)
print(len(df))
df.shape


df.fillna("  ", inplace = True)    
        


# df['Zip Code'] = df['Zip Code'].astype(str).replace('\.0', '', regex=True)

# df.rename(columns={"Where": "Address"}, inplace=True)

# df['Phone Number(s)'] = df['Mobile Number'].map(str) + " | " + df['Home Number'].map(str)


df['Phone Number(s)'] =  df.apply(lambda df: extract_phone_numbers(df['Description']), axis=1)
df['Phone Number(s)'] = df['Phone Number(s)'].apply(', '.join)
df['Email'] = df['Description'].apply(lambda x: extract_email_addresses(x))
# df['Email'] = df.Emails.apply(', '.join)
df.loc[:,'Email'] = df.loc[:,'Email'].astype(str)
df.rename(columns={"Where": "Address"}, inplace=True)
df.loc[:,'Email'] = df.loc[:,'Email'].apply(lambda x: literal_eval(x))
df['Email'] = df['Email'].str.get(0)
df.fillna("  ", inplace = True)  
# df['Name'] = df.apply(lambda df: extract_names(df['Description'], df['Addr"ess']), axis=1)
df['Title'] = df['Title'].apply(lambda x: x.strip(' - '))
df['Title'] = df['Title'].apply(lambda x: x.strip('windows'))
df['Title'] = df['Title'].apply(lambda x: x.strip('Windows'))
df['Title'] = df['Title'].apply(lambda x: x.strip('Clean'))
df['Title'] = df['Title'].apply(lambda x: x.strip('clean'))
df['Title'] = df['Title'].apply(lambda x: x.strip('wash'))
df['Title'] = df['Title'].apply(lambda x: cap_words(x))

# df['Notes'] = df['Notes'].apply(lambda df: df.replace('<br>', '\n'))
df['Description'] = df['Description'].apply(lambda x: replace_html(x))



df['Raw Data'] =  df['Description'].map(str) + "  " + df['Title'].map(str)
df['Raw Data'] = df['Raw Data'].apply(lambda x: replace_html(x))
df['extd Names'] = df['Raw Data'].apply(lambda x: return_rosette(x))

df['Full Name'] = df['extd Names'].apply(lambda df: easy_name(df))
df['Last Name'] = df['Full Name'].apply(lambda df: last_name(df))
df['First Name'] = df['Full Name'].apply(lambda x: first_name(x))
df.fillna("", inplace = True) 
# df['Name'] = df.Name.apply(', '.join)
# df.rename(columns={"Notes": "Raw Data"}, inplace=True)
# df.loc[:,'Phone Number(s)'] = df.loc[:,'Phone Number(s)'].apply(lambda x: literal_eval(x))
# df['Description'] = df['Description'].map(str) + " | " + df['Title'].map(str)



df = df.drop_duplicates(subset=['First Name', 'Last Name', 'Email', 'Address'], keep='first')

df = df[['First Name', 'Last Name', 'Email', 'Phone Number(s)', 'Address', 'Raw Data']]

# 9442
df.to_csv('4-9 MASTER.csv')

# df.to_csv('4-9 Master_p.csv', index=False)

df.columns
df.shape
df[:40]

9442
unsupportedLanguage: Language cat not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language pol not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language pol not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language pol not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language tur not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language est not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language est not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language pol not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language pol not supported:
  https://api.rosette.com/rest/v1/entities
unsupportedLanguage: Language cat not supported:
  https://api.rosette.com/rest/v1/entities

,First Name,Last Name,Email,Phone Number(s),Address,Raw Data
0,Kathy,Reid,,,"2448 Hidden Lake Dr, Woodbury, MN 55125, USA",Kathy Reid
1,,Kathy,,,,Finish Kathy's
2,,,,6124141243,"3541 36th Ave S, Minneapolis, MN 55406, USA",windows - get back to kellie Erickson- text he...
3,Jodi,Jodi,,6514007599,"20259 Wolfram St NW, 20259 Wolfram Street Nort...",651-400-7599 - Jodi Jodi A -
4,Debbie,Hilsen,debrahilsen@hotmail.com,9522403299,"22585 Woodhill Dr, Lakeville, MN 55044, USA",Debbie Hilsen - \n# 952-240-3299\nemail - debr...
5,Julie,Baecker,baecker1@yahoo.com,"6515014862, 6514084696","619 Sterling St S, Maplewood, MN 55119, USA",Julie Baecker\n619 Sterling St. S\nMaplewood\n...
6,Laura,Wright,,,"5112 11th Ave S, Minneapolis, MN 55417, USA",$145.25\nJob went bad - window couldn;t be put...
7,,Rita,,,"2139 Violet Ln, New Brighton, MN 55112, USA",Rita's
8,Kris,Nozal,,6127167298,"11657 Millpond Ave, Burnsville, MN 55337, USA",my unit faces a pond\n612-716-7298 Kris Nozal...
9,Christine Van,Egdom,,7634390087,"1387 Michelle Dr, Eagan, MN 55123, USA",$158.50 (plus tax). -- was 178.50 but dropped...
10,,,,,,Interior At Psc Map
11,Justin,Engels,,"6128682639, 6513346999","1403 Brandlwood Rd, White Bear Township, MN 55...",Wifes number is - 612-868-2639\nJustins is - 6...
13,Dana,Dimit,,6129914913,"5940 Morgan Ave S, Minneapolis, MN 55419, USA",612.991.4913\n$283.50 for all interior and ext...
14,Peggy,Vanelli,,6127022914,"5900 Killarney Ln S, Edina, MN 55436, USA",612-702-2914.\nWas 136 for both interior and e...
15,Brad,Ballinger,,,"1645 W Highland Pkwy, St Paul, MN 55116, USA",$288 for ALL interior and exterior Brad Balli...
16,Diane,Barkdull,,7632322031,"12383 Midway Cir NE, Blaine, MN 55449, USA",Two property locations - one is smaller and on...
17,Emily,Grams,,,"4908 Zenith Ave S, Minneapolis, MN 55410, USA",Total panes - 99\nTotal price - $346.50 for AL...
18,Lesley,Newhouse,,6127200455,"2420 W 106th St, Minneapolis, MN 55431, USA",Lesley phone number - 612-720-0455\nShe will b...
19,Dan,Cole,,,"929 Deer Creek Parkway, Belle Plaine, MN 56011",Dan Cole
20,Pamela,Goldman,phgoldman744@gmail.com,6126195877,"3420 Holmes Ave, Minneapolis, MN 55408, USA",612-619-5877 (cell)\nphgoldman744@gmail.com\nT...
21,Lesley,New,,6127200455,"14509 Spring Lake Rd, Minnetonka, MN 55345, USA",Phone number - 612-720-0455\nShe will be payin...
23,Dan,Solomon,,6129647072,"676 Ashland Avenue #1, Saint Paul, MN",$30 minimum\n612-964-7072 Dan Solomon's
24,Regina,S,,6512761220,"5225 2nd Ave S, Minneapolis, MN 55419, USA",Regina S - $392 + tax. - ended up being $700 p...
25,Diane Barkdull,Lindstrom,,,"30425 Vine St, Lindstrom, MN 55045, USA",Diane Barkdull Lindstrom House Property
26,Susan,Ryan,,6519839235,"4107 Oakbrooke Trail, Eagan, MN 55122, USA",Phone number is - 651-983-9235\n25 panes - int...
27,Suzanne,Trunell,,6512837690,"36 N Oaks Rd, North Oaks, MN 55127, USA",Phone number -651-283-7690\n$186 for exterior ...
29,David,Stevens,,6514266424,"45 Neptune St, St Paul, MN 55115, USA","45 Neptune St, Mahtomedi, MN 55115\n$80.50 plu..."
30,Carol,Wylde,wylderose@comcast.net,,"433 Meadowood Lane, Burnsville",2 stories - can do with 17 foot ladder\nTook 4...
31,Bobby,Haskins,,6126700047,"9666 Unity Ln N, Brooklyn Park, MN 55443, USA",Have not yet given a quote - will give on arri...
32,Ron),Schwerman,eydieathome@gmail,9528847832,"9533 Chicago Ave S, Minneapolis, MN 55420, USA",$190 for ALL windows interior and exterior - t...
33,Bloomington,Locat,,,,Parkinsons Bloomington Locat
34,Matt,Bowar,,7633700612,"549 Portland Ave, St Paul, MN 55102, USA",763-370-0612 Matt Bowar
35,Michelle,Smith,,,,Michelle Smith
36,Adam,Phalen,,6513538910,"2808 Hawk Ridge Road Northwest, Prior Lake, MN...","651-353-8910\nSent pictures over email, estima..."
38,Ellen,Gish,,6123063244,"9165 Archer Ln N, Maple Grove, MN 55311, USA",612-306-3244\nShe is moving - selling house \n...
39,,Savage,,9524408038,"13945 Alabama Ave S, Savage, MN 55378, USA","13945 Alabama Ave S, Savage MN\n2 stories - ca..."
40,Sarah,Traffas,,9529132876,"Idealic Ave, Lakeville, MN 55044, USA",$84 for the outside windows and - 4 - of the i...
41,,Ben,,,"2292 Folwell Ave, Falcon Heights, MN 55108, USA",Ben and Carey Bollinger Danielson\n\nIf there ...
42,Ross,Tano,,6512166470,"16562 Jacaranda Way, Lakeville, MN 55044, USA",16562 Jacaranda Way\n Lakeville\n($170)\n 651-...
43,Peggy,Searles,,6128404752,"17005 5th Ave N, Minneapolis, MN 55447, USA",Cell# 612-840-4752\nShe sent photos over -- ch...

In [131]:
df.to_csv('4-9 MASTER.csv', index=False)

In [49]:
import json
import os
import pprint
from rosette.api import API, DocumentParameters, RosetteException


def run(key, entities_text_data, alt_url='https://api.rosette.com/rest/v1/'):
    """ Run the example """
    # Create an API instance
    api = API(user_key=key, service_url=alt_url)

    # Set selected API options.
    # For more information on the functionality of these
    # and other available options, see Rosette Features & Functions
    # https://developer.rosette.com/features-and-functions#entity-extraction-and-linking

    # api.set_option('calculateSalience','true')
    # api.set_option('linkEntities','false')


    params = DocumentParameters()
    params["content"] = entities_text_data
    params["genre"] = "social-media"
    try:
        return api.entities(params)
    except RosetteException as exception:
        print(exception)

def return_rosette(x):
    RESULT = run(key='8ef3dd8a2669509d1165bcf5e21596e7', entities_text_data=x)
    RESULT = json.dumps(RESULT, indent=2, ensure_ascii=False, sort_keys=True)
    RESULT = json.loads(RESULT)
    
    target_facet_name = 'PERSON'
    for record in RESULT["entities"]:
        if record["type"] == target_facet_name:
            print(record["normalized"])
            
            
#     print(len(RESULT['entities']))
# ['entities'][0]['normalized']

return_rosette(df.iloc[22][4])

Pamela Goldman

In [218]:

    
    
    

# mask = df.my_channel > 20000
# column_name = 'my_channel'
# df.loc[mask, column_name] = 0

new = df["Name"].str.split(" ",1, expand = True) 
new
df["First Name"]= new[0] 
  
# making separate last name column from new data frame 
df["Last Name"]= new[1] 
# df[['First', 'Last']] = df['Name'].split(' ', 1)

# df[['First', 'Last']] = df['Name'].split(' ', 1)

new = df["Name"].str.split(" ",1, expand = True) 

df["First Name"]= new[0] 
  
df["Last Name"]= new[1] 


    
# # df['Zip'] = df['Zip'].astype(str).replace('\.0', '', regex=True)

# # df.rename(columns={"First ": "First Name"}, inplace=True)

# df.rename(columns={'Email Address': "Email"}, inplace=True)
# df["Address"] = ""
# df['Phone Number(s)'] = ""
# # df.rename(columns={"Main Phone #s": "Phone Number(s)"}, inplace=True)

# # df['Phone Number(s)'] = df['Mobile Phone #s'].map(str) + " " + df['Other Phone #s'].map(str)
# # df['Address'] = df['Service Street 1'].map(str) + " " + df['Service City'].map(str) + " " + df['Service State'].map(str) + " " + df['Service Country'].map(str) + " " + df['Service ZIP code'].map(str)

# df = df[['First Name', 'Last Name', 'Email', 'Phone Number(s)', 'Address']]

KeyError: 1

In [178]:
df.iloc[49]
"""
Name                                Charlene and Bruce Olson
Address      11004 Territorial Dr, Burnsville, MN 55337, USA
Notes      Charlene and Bruce Olson\nolson9family@yahoo.c...
Notes 2         11004 Territorial Drive\nBurnsville,mn 55337
Name: 49, dtype: object
"""

'\nName                                Charlene and Bruce Olson\nAddress      11004 Territorial Dr, Burnsville, MN 55337, USA\nNotes      Charlene and Bruce Olson\nolson9family@yahoo.c...\nNotes 2         11004 Territorial Drive\nBurnsville,mn 55337\nName: 49, dtype: object\n'

In [177]:
df.iloc[49][2]
"""
Charlene and Bruce Olson\nolson9family@yahoo.com\nbruce@truestonecoffee.com\n11004 Territorial Dr, Burnsville, MN 55337, 
USA\n612-501-6937\n\n8-10 am arrival time\n\n$160 plus tax for the interior and exterior panes of glass as well as the 
screens and sills\n\n------\n$160 plus tax = $172.44\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWindow Cleaning\nFri, 
Mar 10 at 09:00 AM (4 hours)\n<A href='http://maps.google.com/?q=11004%20Territorial%20Drive%0ABurnsville,mn%2055337' 
target='_blank'>Appointment will be held at: 11004 Territorial Drive\nBurnsville,mn 55337</A>\nNotes\t\t\t\tYou did a 
fantastic job last time!  We are putting our house on the market on Monday the 13th so would really appreciate clean 
windows!\n\n\nTo make changes to the appointment, please follow this link: 
https://www.vcita.com/engagements/haq8bbncx10tsxr8?meeting_action=view&meeting_id=4029aac71f39f3ab&email_token
=37348fc469f7a82fe17b&from_email=true&owner=true&flow=Email_Action&flow_origin=accepted_notification&flow_action
=view_appointment\n\n\nFull details on Charlene Olson, Click Here: https://www.vcita.com/clients/?client=o2pun84hy2c31eb8&flow
=Email_Action&flow_origin=accepted_notification&flow_action=view_contact_details#/o2pun84hy2c31eb8\nEmail\t
\t\t\tolson9family@yahoo.com, Click Here: mailto:olson9family@yahoo.com\nPhone\t\t\t\t612-501-6937\nAddress\t\t\t\t<A 
href='http://maps.google.com/?q=11004%20Territorial%20Drive%0ABurnsville,mn%2055337' target='_blank'>
11004 Territorial Drive\nBurnsville,mn 55337</A>\nGender\t\t\t\tFemale\nSource\t\t\t\tLiveSite Widget\n
Facebook Profile, Click Here: https://www.facebook.com/charlene.olson.35\n|
"""

"\nCharlene and Bruce Olson\nolson9family@yahoo.com\nbruce@truestonecoffee.com\n11004 Territorial Dr, Burnsville, MN 55337, \nUSA\n612-501-6937\n\n8-10 am arrival time\n\n$160 plus tax for the interior and exterior panes of glass as well as the \nscreens and sills\n\n------\n$160 plus tax = $172.44\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWindow Cleaning\nFri, \nMar 10 at 09:00 AM (4 hours)\n<A href='http://maps.google.com/?q=11004%20Territorial%20Drive%0ABurnsville,mn%2055337' \ntarget='_blank'>Appointment will be held at: 11004 Territorial Drive\nBurnsville,mn 55337</A>\nNotes\t\t\t\tYou did a \nfantastic job last time!  We are putting our house on the market on Monday the 13th so would really appreciate clean \nwindows!\n\n\nTo make changes to the appointment, please follow this link: \nhttps://www.vcita.com/engagements/haq8bbncx10tsxr8?meeting_action=view&meeting_id=4029aac71f39f3ab&email_token\n=37348fc469f7a82fe17b&from_email=true&owner=true&flow=Email_Action&flow_origin=accepted_notification&flow_action\n=view_appointment\n\n\nFull details on Charlene Olson, Click Here: https://www.vcita.com/clients/?client=o2pun84hy2c31eb8&flow\n=Email_Action&flow_origin=accepted_notification&flow_action=view_contact_details#/o2pun84hy2c31eb8\nEmail\t\n\t\t\tolson9family@yahoo.com, Click Here: mailto:olson9family@yahoo.com\nPhone\t\t\t\t612-501-6937\nAddress\t\t\t\t<A \nhref='http://maps.google.com/?q=11004%20Territorial%20Drive%0ABurnsville,mn%2055337' target='_blank'>\n11004 Territorial Drive\nBurnsville,mn 55337</A>\nGender\t\t\t\tFemale\nSource\t\t\t\tLiveSite Widget\n\nFacebook Profile, Click Here: https://www.facebook.com/charlene.olson.35\n|\n"

In [39]:
import argparse
import json
import os

from rosette.api import API, DocumentParameters, RosetteException


def run(key, alt_url='https://api.rosette.com/rest/v1/'):
    """ Run the example """
    # Create an API instance
    api = API(user_key=key, service_url=alt_url)

    # Set selected API options.
    # For more information on the functionality of these
    # and other available options, see Rosette Features & Functions
    # https://developer.rosette.com/features-and-functions#entity-extraction-and-linking

    # api.set_option('calculateSalience','true')
    # api.set_option('linkEntities','false')

    entities_text_data = df.iloc[2][-1]
    params = DocumentParameters()
    params["content"] = entities_text_data
    params["genre"] = "social-media"
    try:
        return api.entities(params)
    except RosetteException as exception:
        print(exception)


RESULT = run('8ef3dd8a2669509d1165bcf5e21596e7', "https://api.rosette.com/rest/v1/")
RESULT = json.dumps(RESULT, indent=2, ensure_ascii=False, sort_keys=True)
RESULT = json.loads(RESULT)
print(RESULT)
# print(json.dumps(RESULT, indent=2, ensure_ascii=False, sort_keys=True).encode("utf8"))

{'entities': [{'confidence': 0.10147262, 'count': 2, 'entityId': 'T1', 'mention': 'Kellie Erick', 'mentionOffsets': [{'endOffset': 23, 'startOffset': 11}, {'endOffset': 73, 'startOffset': 70}], 'normalized': 'Kellie Erick', 'type': 'PERSON'}, {'confidence': 0.7234118, 'count': 1, 'entityId': 'Q1406', 'linkingConfidence': 0.251316, 'mention': 'Windows', 'mentionOffsets': [{'endOffset': 8, 'startOffset': 1}], 'normalized': 'Microsoft Windows', 'type': 'PRODUCT'}, {'count': 1, 'entityId': 'T2', 'mention': '612-414-1243', 'mentionOffsets': [{'endOffset': 89, 'startOffset': 77}], 'normalized': '612-414-1243', 'type': 'IDENTIFIER:PHONE_NUMBER'}, {'count': 1, 'entityId': 'T3', 'mention': '2:30', 'mentionOffsets': [{'endOffset': 94, 'startOffset': 90}], 'normalized': '2:30', 'type': 'TEMPORAL:TIME'}, {'count': 1, 'entityId': 'T4', 'mention': 'friday', 'mentionOffsets': [{'endOffset': 101, 'startOffset': 95}], 'normalized': 'friday', 'type': 'TEMPORAL:DATE'}, {'count': 1, 'entityId': 'T5', 'mention': '$ 6', 'mentionOffsets': [{'endOffset': 179, 'startOffset': 176}], 'normalized': '$ 6', 'type': 'IDENTIFIER:MONEY'}], 'responseHeaders': {'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Content-Type': 'application/json', 'Date': 'Mon, 27 Apr 2020 18:39:25 GMT', 'Server': 'openresty', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Transfer-Encoding': 'chunked', 'Vary': 'Accept-Encoding', 'X-RosetteAPI-App-Id': '1409619781209', 'X-RosetteAPI-Concurrency': '1', 'X-RosetteAPI-ProcessedLanguage': 'eng', 'X-RosetteAPI-Request-Id': '319913b8b8d8678143c8850416b57900'}}

In [63]:
RESULT['entities'][0]['normalized']

'Kellie Erick'